# Generated by Django 5.2.4 on 2025-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_stock_discount_percentage_alter_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
