# Generated by Django 5.2.4 on 2025-09-06 10:17

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_stock_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(db_index=True, default='Unknown', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('nationality'), name='unique_author_name_nationality_ci'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'publication_date', 'publisher'), name='unique_book_title_pubdate_publisher'),
        ),
        migrations.AddConstraint(
            model_name='publisher',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_publisher_name_ci'),
        ),
    ]
