# Generated by Django 5.2.4 on 2025-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_author_nationality_alter_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
