# Generated by Django 5.2.4 on 2025-11-06 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_stock_price_c0622b_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_stock_stock_q_8ecd93_idx',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='discount_percentage',
            new_name='current_discount_percentage',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='current_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_quantity',
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['current_price'], name='stock_stock_current_e99121_idx'),
        ),
    ]
