# Generated by Django 5.2.4 on 2025-11-06 11:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('orders', '0001_initial'),
        ('stock', '0002_remove_stock_stock_stock_price_c0622b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this object was deleted', null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this object was deleted', null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['received_date'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this object was deleted', null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('restock', 'Restock'), ('reserve', 'Reserve for Order'), ('release_reserve', 'Release Reservation'), ('refund', 'Refund/Return')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('before_quantity', models.PositiveIntegerField()),
                ('after_quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this object was deleted', null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserved_quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_stock_is_avai_01dd78_idx',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stock.stock'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.stock'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.publisher'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='stock.stockbatch'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='stock.stock'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stock.stockbatch'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='orders.orderitem'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['stock', '-created_at'], name='stock_price_stock_i_3fe590_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['stock', 'received_date'], name='stock_stock_stock_i_f869a9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['remaining_quantity'], name='stock_stock_remaini_a665e2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['stock', '-created_at'], name='stock_stock_stock_i_71c294_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['change_type'], name='stock_stock_change__886fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order_item', 'is_active'], name='stock_stock_order_i_d14b02_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['batch'], name='stock_stock_batch_i_dc2ada_idx'),
        ),
    ]
