# Generated by Django 5.2.4 on 2025-11-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_pricehistory_stockbatch_stockhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stock.stock'),
            preserve_default=False,
        ),
    ]
