# Generated by Django 5.2.4 on 2025-11-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('stock', '0004_stockreservation_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='change_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('reserve', 'Reserve for Order'), ('release_reserve', 'Release Reservation'), ('sold', 'Sold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='orders.orderitem'),
        ),
    ]
