# Generated by Django 5.2.4 on 2025-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockhistory_change_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='after_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='before_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
