# Generated by Django 5.2.4 on 2025-11-12 03:48

import django.core.validators
import django.utils.timezone
import src.core.validators.dates
import src.core.validators.numbers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stockhistory_after_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='initial_quantity',
            field=models.PositiveIntegerField(validators=[src.core.validators.numbers.validate_minimum_stock]),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='notes',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[src.core.validators.dates.validate_date, src.core.validators.dates.validate_past_dates]),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), src.core.validators.numbers.validate_positive_integer]),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='change_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('editstock', 'Edit Stock'), ('reserve', 'Reserve for Order'), ('release_reserve', 'Release Reservation'), ('sold', 'Sold')], max_length=20),
        ),
    ]
