# Generated by Django 5.2.4 on 2025-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stockbatch_initial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='change_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('editstock', 'Edit Stock'), ('reserve', 'Reserve for Order'), ('sold', 'Sold')], max_length=20),
        ),
    ]
