# Generated by Django 5.2.4 on 2025-11-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_stockhistory_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='change_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('editstock', 'Edit Stock'), ('reserve', 'Reserve for Order'), ('release_reserve', 'Release Reservation'), ('sold', 'Sold')], max_length=20),
        ),
    ]
